name: louisroyer-gh-actions/busted
description: Busted
inputs:
  args:
    description: Arguments passed to busted
    required: false
    default: "."
runs:
  using: docker
  image: docker://ghcr.io/louisroyer-gh-actions/busted:latest
  args:
    - ${{ inputs.args }}
branding:
  icon: check
  color: yellow

