name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_call:

jobs:
   docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ CI_REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ CI_REPOSITORY  }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

